/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gftech_sales;

import com.mysql.cj.protocol.Resultset;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
//import java.sql.ResultSetMetaProduct;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author leon
 */
public class GFTECH_product_form extends javax.swing.JFrame {

    /** Creates new form GFTECH_product_form */
    public GFTECH_product_form() {
        initComponents();
        scaleImage();
        this.setLocationRelativeTo(null);
        load();
        updateCombo();
        setIcon();
        this.setTitle("GFTECH_System");
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/GFTECH logo.jpg")));
    }

    public void updateCombo(){
//        Connection con=null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        String query = "select * from gftech_category";
        try {
        Connection con = DriverManager.getConnection("jdbc:sqlite:gftech_db.db");
        pst = con.prepareStatement(query);
        rs = pst.executeQuery();
        while(rs.next()){
            jComboBox_product_category.addItem(rs.getString("Name"));
        }
        pst.close();
        con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error!!!"+ e);
        }
        
    }
    

    public void load(){
        try {
            Connection con = DriverManager.getConnection("jdbc:sqlite:gftech_db.db");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from gftech_product");
            jTable_products.setModel(DbUtils.resultSetToTableModel(rs));
            stmt.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    
     public void scaleImage(){
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/GFTECH logo.jpg"));
        //Scaling image
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(jLabel_gftech_logo.getWidth(), jLabel_gftech_logo.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        jLabel_gftech_logo.setIcon(scaledIcon);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_title = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_gftech_logo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_product_id = new javax.swing.JLabel();
        jLabel_product_name = new javax.swing.JLabel();
        jLabel_product_price = new javax.swing.JLabel();
        jLabel_product_category = new javax.swing.JLabel();
        jButton_insert = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jTextField_product_name = new javax.swing.JTextField();
        jButton_search = new javax.swing.JButton();
        jComboBox_product_category = new javax.swing.JComboBox<>();
        jTextField_product_price = new javax.swing.JTextField();
        jTextField_product_id = new javax.swing.JTextField();
        jLabel_product_quantity = new javax.swing.JLabel();
        jTextField_product_quantity = new javax.swing.JTextField();
        jButton_home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_products = new javax.swing.JTable();
        jLabel_productlist = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(175, 175, 175));

        jPanel2.setBackground(new java.awt.Color(254, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_title.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_title.setText("GFTECH INVESMENTS PRODUCT MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_gftech_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_gftech_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_title, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(391, 391, 391)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel_title, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setOpaque(false);

        jLabel_product_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_product_id.setForeground(new java.awt.Color(254, 0, 0));
        jLabel_product_id.setText("ID:");

        jLabel_product_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_product_name.setForeground(new java.awt.Color(254, 0, 0));
        jLabel_product_name.setText("Name:");

        jLabel_product_price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_product_price.setForeground(new java.awt.Color(254, 0, 0));
        jLabel_product_price.setText("Price:");

        jLabel_product_category.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_product_category.setForeground(new java.awt.Color(254, 0, 0));
        jLabel_product_category.setText("Category:");

        jButton_insert.setBackground(new java.awt.Color(254, 0, 0));
        jButton_insert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_insert.setForeground(new java.awt.Color(255, 255, 255));
        jButton_insert.setText("ADD");
        jButton_insert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertActionPerformed(evt);
            }
        });

        jButton_update.setBackground(new java.awt.Color(254, 0, 0));
        jButton_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update.setText("EDIT");
        jButton_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jButton_delete.setBackground(new java.awt.Color(254, 0, 0));
        jButton_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton_delete.setText("DELETE");
        jButton_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_clear.setBackground(new java.awt.Color(254, 0, 0));
        jButton_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_clear.setForeground(new java.awt.Color(255, 255, 255));
        jButton_clear.setText("CLEAR");
        jButton_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jTextField_product_name.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jTextField_product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_product_nameActionPerformed(evt);
            }
        });

        jButton_search.setBackground(new java.awt.Color(254, 0, 0));
        jButton_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_search.setForeground(new java.awt.Color(255, 255, 255));
        jButton_search.setText("SEARCH");
        jButton_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        jComboBox_product_category.setBackground(new java.awt.Color(254, 0, 0));
        jComboBox_product_category.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox_product_category.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_product_category.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTextField_product_price.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jTextField_product_id.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jLabel_product_quantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_product_quantity.setForeground(new java.awt.Color(254, 0, 0));
        jLabel_product_quantity.setText("Quantity");

        jTextField_product_quantity.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N

        jButton_home.setBackground(new java.awt.Color(254, 0, 0));
        jButton_home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_home.setForeground(new java.awt.Color(255, 255, 255));
        jButton_home.setText("HOME");
        jButton_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_product_quantity)
                            .addComponent(jLabel_product_price)
                            .addComponent(jLabel_product_name)
                            .addComponent(jLabel_product_id)
                            .addComponent(jButton_insert)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_product_category)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox_product_category, javax.swing.GroupLayout.Alignment.LEADING, 0, 182, Short.MAX_VALUE)
                            .addComponent(jTextField_product_price, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_product_name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_product_id, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_product_quantity, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(36, 36, 36)
                        .addComponent(jButton_search)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jButton_delete)
                        .addGap(29, 29, 29)
                        .addComponent(jButton_clear)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton_home)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_product_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_product_id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_product_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_search))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_product_price, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_product_price, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_product_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_product_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox_product_category, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel_product_category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_update, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton_home, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jTable_products.setBackground(new java.awt.Color(175, 175, 175));
        jTable_products.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTable_products.setFont(new java.awt.Font("Dubai", 1, 15)); // NOI18N
        jTable_products.setForeground(new java.awt.Color(0, 0, 0));
        jTable_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Quantity", "Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_products.setRowHeight(20);
        jTable_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_products);

        jLabel_productlist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_productlist.setForeground(new java.awt.Color(254, 0, 0));
        jLabel_productlist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_productlist.setText("Product list");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_productlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_productlist, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_product_nameActionPerformed

    private void jButton_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertActionPerformed
        if(jTextField_product_id.getText().isEmpty()||jTextField_product_name.getText().isEmpty()||
                jTextField_product_price.getText().isEmpty()||jTextField_product_quantity.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Cannot store empty field!!!");
        }else
        try {
            Class.forName("org.sqlite.JDBC");
            Connection con = DriverManager.getConnection("jdbc:sqlite:gftech_db.db");
            Statement stmt = con.createStatement();
            String query = "insert into gftech_product (ID, Name, Price,  Category, Quantity) values ('"+jTextField_product_id.getText()+"', '"+jTextField_product_name.getText()+"', '"+jTextField_product_price.getText()+"', '"+jComboBox_product_category.getSelectedItem().toString()+"', '"+jTextField_product_quantity.getText()+"')";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Product Successfully inserted!!!");
            load();
            stmt.close();
            con.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error!!! "+ex);
        }
    }//GEN-LAST:event_jButton_insertActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        try {
            Class.forName("org.sqlite.JDBC");
            Connection con = DriverManager.getConnection("jdbc:sqlite:gftech_db.db");
//            Statement stmt = con.createStatement();
            String query = "select * from gftech_product where Name = '"+jTextField_product_name.getText()+"' ";
            PreparedStatement stmt = con.prepareStatement(query);
//            stmt.executeUpdate(query);
            ResultSet set = stmt.executeQuery();
            while(set.next()){
                jTextField_product_id.setText(set.getString("ID"));
                jTextField_product_name.setText(set.getString("Name"));
                jTextField_product_price.setText(set.getString("Price"));
                jTextField_product_quantity.setText(set.getString("Quantity"));
                jComboBox_product_category.setSelectedItem(set.getString("Category"));
            }
            stmt.close();
            con.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error!!! "+ex);
        }
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        jTextField_product_id.setText(null);
        jTextField_product_name.setText(null);
        jTextField_product_price.setText(null);
        jTextField_product_quantity.setText(null);
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        if(jTextField_product_id.getText().isEmpty()||jTextField_product_name.getText().isEmpty()||
                jTextField_product_price.getText().isEmpty()||jTextField_product_quantity.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Cannot store empty field!!!");
        }else
        try {
            Class.forName("org.sqlite.JDBC");
            Connection con = DriverManager.getConnection("jdbc:sqlite:gftech_db.db");
            Statement stmt = con.createStatement();
            String query = "update gftech_product set Name = '"+jTextField_product_name.getText()+"',  Price = '"+jTextField_product_price.getText()+"', Category = '"+jComboBox_product_category.getSelectedItem().toString()+"', Quantity = '"+jTextField_product_quantity.getText()+"' where ID ='"+jTextField_product_id.getText()+"'";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Product Successfully updated!!!");
            load();
            stmt.close();
            con.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error!!! "+ex);
        }
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        try {
            Class.forName("org.sqlite.JDBC");
            Connection con = DriverManager.getConnection("jdbc:sqlite:gftech_db.db");
            Statement stmt = con.createStatement();
            String query = "delete from gftech_product where ID = '"+jTextField_product_id.getText()+"'";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Product Successfully deleted!!!");
            load();
            stmt.close();
            con.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error!!! "+ex);
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        GFTECH_Dashboard ds = new GFTECH_Dashboard();
        ds.setVisible(true);
        ds.pack();
        ds.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jTable_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productsMouseClicked
        DefaultTableModel model = (DefaultTableModel)jTable_products.getModel();
        int index = jTable_products.getSelectedRow();
        jTextField_product_id.setText(model.getValueAt(index, 0).toString());
        jTextField_product_name.setText(model.getValueAt(index, 1).toString());
        jTextField_product_price.setText(model.getValueAt(index, 2).toString());
        jTextField_product_quantity.setText(model.getValueAt(index, 4).toString());
    }//GEN-LAST:event_jTable_productsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GFTECH_product_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GFTECH_product_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GFTECH_product_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GFTECH_product_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GFTECH_product_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_home;
    private javax.swing.JButton jButton_insert;
    private javax.swing.JButton jButton_search;
    private javax.swing.JButton jButton_update;
    private javax.swing.JComboBox<String> jComboBox_product_category;
    private javax.swing.JLabel jLabel_gftech_logo;
    private javax.swing.JLabel jLabel_product_category;
    private javax.swing.JLabel jLabel_product_id;
    private javax.swing.JLabel jLabel_product_name;
    private javax.swing.JLabel jLabel_product_price;
    private javax.swing.JLabel jLabel_product_quantity;
    private javax.swing.JLabel jLabel_productlist;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_products;
    private javax.swing.JTextField jTextField_product_id;
    private javax.swing.JTextField jTextField_product_name;
    private javax.swing.JTextField jTextField_product_price;
    private javax.swing.JTextField jTextField_product_quantity;
    // End of variables declaration//GEN-END:variables


}
