/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gftech_sales;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author leon
 */
public class GFTECH_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form GFTECH_Dashboard
     */
    public GFTECH_Dashboard() {
        initComponents();
        scaleImagelogo();
        scaleImageProduct();
        scaleImageCustomer();
        scaleImageCategory();
        scaleImageUser();
        scaleImageOrder();
        this.setLocationRelativeTo(null);
        setIcon();
        this.setTitle("GFTECH_System");
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/GFTECH logo.jpg")));
    }
        
     public void scaleImagelogo(){
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/GFTECH logo.jpg"));
        //Scaling image
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(jLabel_gftech_logo3.getWidth(), jLabel_gftech_logo3.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        jLabel_gftech_logo3.setIcon(scaledIcon);
    }
     
     public void scaleImageProduct(){
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/product_icon2.png"));
        
        //Scaling image
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(jLabel_product_icon.getWidth(), jLabel_product_icon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        jLabel_product_icon.setIcon(scaledIcon);
    }
     
     public void scaleImageCustomer(){
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/customer_icon1.png"));
        //Scaling image
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(jLabel_customer_icon.getWidth(), jLabel_customer_icon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        jLabel_customer_icon.setIcon(scaledIcon);
    }
     
     public void scaleImageCategory(){
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/category_icon.png"));
        //Scaling image
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(jLabel_category_icon.getWidth(), jLabel_category_icon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        jLabel_category_icon.setIcon(scaledIcon);
    }
     
     public void scaleImageUser(){
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/user_icon.png"));
        //Scaling image
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(jLabel_users_icon.getWidth(), jLabel_users_icon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        jLabel_users_icon.setIcon(scaledIcon);
    }
     
     public void scaleImageOrder(){
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/orders_icon1.png"));
        //Scaling image
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(jLabel_order_icon.getWidth(), jLabel_order_icon.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgscale);
        jLabel_order_icon.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel_title3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel_gftech_logo3 = new javax.swing.JLabel();
        jButton_logout = new javax.swing.JButton();
        jLabel_products = new javax.swing.JLabel();
        jLabel_product_icon = new javax.swing.JLabel();
        jLabel_order_icon = new javax.swing.JLabel();
        jLabel_orders = new javax.swing.JLabel();
        jLabel_category_icon = new javax.swing.JLabel();
        jLabel_category = new javax.swing.JLabel();
        jLabel_customer_icon = new javax.swing.JLabel();
        jLabel_customers = new javax.swing.JLabel();
        jLabel_users_icon = new javax.swing.JLabel();
        jLabel_users = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(254, 0, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_title3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel_title3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_title3.setText("GFTECH INVESMENTS INVENTORY MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_gftech_logo3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_gftech_logo3, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_title3, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(403, 403, 403)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel_title3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton_logout.setBackground(new java.awt.Color(254, 0, 0));
        jButton_logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_logout.setForeground(new java.awt.Color(255, 255, 255));
        jButton_logout.setText("LOG OUT");
        jButton_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });

        jLabel_products.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_products.setForeground(new java.awt.Color(254, 0, 0));
        jLabel_products.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_products.setText("Products");

        jLabel_product_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_product_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_product_iconMouseClicked(evt);
            }
        });

        jLabel_order_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_order_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_order_iconMouseClicked(evt);
            }
        });

        jLabel_orders.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_orders.setForeground(new java.awt.Color(254, 0, 0));
        jLabel_orders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_orders.setText("Orders");

        jLabel_category_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_category_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_category_iconMouseClicked(evt);
            }
        });

        jLabel_category.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_category.setForeground(new java.awt.Color(254, 0, 0));
        jLabel_category.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_category.setText("Category");

        jLabel_customer_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_customer_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_customer_iconMouseClicked(evt);
            }
        });

        jLabel_customers.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_customers.setForeground(new java.awt.Color(254, 0, 0));
        jLabel_customers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_customers.setText("Customers");

        jLabel_users_icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_users_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_users_iconMouseClicked(evt);
            }
        });

        jLabel_users.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_users.setForeground(new java.awt.Color(254, 0, 0));
        jLabel_users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_users.setText("Users");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel_category_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_products, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_product_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)))
                .addComponent(jLabel_customer_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_category, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel_order_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_customers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_users, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButton_logout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_users_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_customers, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_customer_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_category, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_category_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabel_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_order_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel_users, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_users_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel_products, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_product_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_category_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_category_iconMouseClicked
        GFTECH_category_form ct = new GFTECH_category_form();
        ct.setVisible(true);
        ct.setLocationRelativeTo(null);
        ct.pack();
        this.dispose();
    }//GEN-LAST:event_jLabel_category_iconMouseClicked

    private void jLabel_order_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_order_iconMouseClicked
        GFTECH_order_form od = new GFTECH_order_form();
        od.setVisible(true);
        od.pack();
        od.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_order_iconMouseClicked

    private void jLabel_product_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_product_iconMouseClicked
        GFTECH_product_form pd = new GFTECH_product_form();
        pd.setVisible(true);
        pd.pack();
        pd.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_product_iconMouseClicked

    private void jLabel_customer_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_customer_iconMouseClicked
        GFTECH_customer_form cs = new GFTECH_customer_form();
        cs.setVisible(true);
        cs.pack();
        cs.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_customer_iconMouseClicked

    private void jLabel_users_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_users_iconMouseClicked
        GFTECH_user_admin usa = new GFTECH_user_admin();
        usa.setVisible(true);
        usa.pack();
        usa.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_users_iconMouseClicked

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        GFTECH_login lg = new GFTECH_login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GFTECH_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GFTECH_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GFTECH_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GFTECH_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GFTECH_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_logout;
    private javax.swing.JLabel jLabel_category;
    private javax.swing.JLabel jLabel_category_icon;
    private javax.swing.JLabel jLabel_customer_icon;
    private javax.swing.JLabel jLabel_customers;
    private javax.swing.JLabel jLabel_gftech_logo3;
    private javax.swing.JLabel jLabel_order_icon;
    private javax.swing.JLabel jLabel_orders;
    private javax.swing.JLabel jLabel_product_icon;
    private javax.swing.JLabel jLabel_products;
    private javax.swing.JLabel jLabel_title3;
    private javax.swing.JLabel jLabel_users;
    private javax.swing.JLabel jLabel_users_icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
